from gradle:7.5-jdk17-focal

USER root
volume /cache

run rm /etc/localtime && \
    ln -fs /usr/share/zoneinfo/America/Chicago /etc/localtime && \
    mkdir /usr/share/jenkins && \
    chown gradle:gradle /cache && \
    apt-get update && \
    apt-get install -y iputils-ping

user gradle

add agent.jar /usr/share/jenkins/agent.jar
