from bfincher/ubuntu-java11:bionic

run apt-get update && \
    apt-get install -y --no-install-recommends ssh \
        git \
        sudo \
        python3-virtualenv \
        virtualenv \
        openjdk-11-jdk-headless \
        libswt-gtk-4-jni \
        python3 \
        python3-setuptools \
        python3-distutils \
        curl \
        unzip \
        net-tools \
        ctags \
        openssh-server \
        openssh-client \
        net-tools && \
    apt-get clean && \
    ssh-keygen -A && \
    export DEBIAN_FRONTEND=noninteractive && \
    ln -fs /usr/share/zoneinfo/America/Chicago /etc/localtime && \
    apt-get install -y --no-install-recommends tzdata && \
    curl -sS https://bootstrap.pypa.io/get-pip.py > setup.py && \
    python3 setup.py && \
    rm setup.py && \
    ln -s /usr/bin/python3.6 /usr/bin/python && \
    ln -s /usr/bin/pip3 /usr/bin/pip && \
    pip3 install virtualenvwrapper

VOLUME /code 

EXPOSE 22

copy root/ /
