from bfincher/alpine-java11:3.13

run apk add --no-cache openssh-client \
    git \
    sudo \
    vim \
    ctags \
    python3 \
    ipython \
    openssh && \
    ssh-keygen -A && \
    sed -i 's/X11Forwarding no/X11Forwarding yes/g' /etc/ssh/sshd_config && \
    ln -s /usr/bin/python3.8 /usr/bin/python && \
    wget https://bootstrap.pypa.io/get-pip.py && \
    python3 get-pip.py && \
    pip3 install virtualenvwrapper

VOLUME /code 

copy root/ /

EXPOSE 22
