from bfincher/alpine-base:3.12

run apk add --no-cache openjdk11-jdk && \
    ln -s /usr/lib/jvm/java-11-openjdk/bin/javac /usr/bin/javac && \
    ln -s /usr/lib/jvm/java-11-openjdk/bin/jar /usr/bin/jar
