#!/usr/bin/with-contenv bash 

getent group $GROUPNAME > /dev/null
if [ $? -eq 0 ]; then
    groupmod -g $GROUPID $GROUPNAME
else
    groupadd -g $GROUPID $GROUPNAME
fi

getent passwd $USERNAME > /dev/null
if [ $? -eq 0 ]; then
    usermod -u $USERID $USERNAME
else
    useradd $USERNAME -u $USERID -g $GROUPID -m -d $HOMEDIR -s /bin/bash
fi

